/**
 * Canonical Chote Bade menu — shared by seed, PetPooja fake sync, and customer fallback.
 * Prices are INR stored as paise (×100).
 */

export const MENU_CATEGORY_ORDER = [
  'SIGNATURE PICKS',
  'PASTA',
  'WRAPS & BOWLS',
  'HUMMUS & GARLIC BREAD',
  'GOURMET SANDWICHES',
  'NACHOS & SNACKS',
  'FRIES & NIBBLES',
  'WOODFIRED PIZZA',
  'BURGERS',
  'FRESH SALADS',
  'WAFFLES & PANCAKES',
  'DESSERTS',
  'CHOTE BADE BARISTA',
  'REFRESHERS',
] as const

export type MenuCategory = (typeof MENU_CATEGORY_ORDER)[number]

/** Filter chip labels — keep close to the printed menu section titles. */
export const MENU_CATEGORY_CHIP: Record<string, string> = {
  'SIGNATURE PICKS': 'Signature Picks',
  PASTA: 'Pasta',
  'WRAPS & BOWLS': 'Wraps & Bowls',
  'HUMMUS & GARLIC BREAD': 'Hummus & Garlic Bread',
  'GOURMET SANDWICHES': 'Gourmet Sandwiches',
  'NACHOS & SNACKS': 'Nachos & Snacks',
  'FRIES & NIBBLES': 'Fries & Nibbles',
  'WOODFIRED PIZZA': 'Woodfired Pizza',
  BURGERS: 'Burgers',
  'FRESH SALADS': 'Fresh Salads',
  'WAFFLES & PANCAKES': 'Waffles & Pancakes',
  DESSERTS: 'Desserts',
  'CHOTE BADE BARISTA': 'Chote Bade Barista',
  REFRESHERS: 'Refreshers',
}

export type CafeMenuSeedItem = {
  petpoojaItemId: string
  name: string
  description: string
  /** Price in paise. */
  price: number
  category: string
  isAvailable: boolean
  /** Optional nutrition for UI badges (not stored in DB). */
  nutrition?: { kcal: number; proteinG: number; fiberG: number }
}

const rupees = (n: number) => n * 100
const n = (kcal: number, proteinG: number, fiberG: number) => ({ kcal, proteinG, fiberG })

/**
 * Home-category items. Signature picks also appear under SIGNATURE PICKS
 * via SIGNATURE_ITEM_IDS on the client.
 */
export const CAFE_MENU_SEED: CafeMenuSeedItem[] = [
  // —— PASTA ——
  {
    petpoojaItemId: 'pp-white-sauce-pasta',
    name: 'White Sauce Pasta',
    description: 'Silky white sauce, soft and familiar.',
    price: rupees(249),
    category: 'PASTA',
    isAvailable: true,
    nutrition: n(620, 18, 5),
  },
  {
    petpoojaItemId: 'pp-red-sauce-pasta',
    name: 'Red Sauce Pasta',
    description: 'Tomato heat with a quiet kick.',
    price: rupees(229),
    category: 'PASTA',
    isAvailable: true,
    nutrition: n(520, 17, 7),
  },
  {
    petpoojaItemId: 'pp-pesto-sauce-pasta',
    name: 'Pesto Sauce Pasta',
    description: 'Basil, cheese, and a green kind of comfort.',
    price: rupees(299),
    category: 'PASTA',
    isAvailable: true,
    nutrition: n(610, 17, 5),
  },
  {
    petpoojaItemId: 'pp-makhani-pasta',
    name: 'Makhani Pasta',
    description: 'Our house makhani — rich, slow, signature.',
    price: rupees(279),
    category: 'PASTA',
    isAvailable: true,
    nutrition: n(650, 20, 6),
  },

  // —— WRAPS & BOWLS ——
  {
    petpoojaItemId: 'pp-mexican-yellow-rice-tofu',
    name: 'Mexican Yellow Rice with Tofu',
    description: 'Colour, crunch, and a full spoon every time.',
    price: rupees(299),
    category: 'WRAPS & BOWLS',
    isAvailable: true,
    nutrition: n(520, 18, 8),
  },
  {
    petpoojaItemId: 'pp-veggie-wrap',
    name: 'Veggie Wrap',
    description: 'Crisp greens, rolled tight for the table.',
    price: rupees(199),
    category: 'WRAPS & BOWLS',
    isAvailable: true,
    nutrition: n(430, 13, 7),
  },
  {
    petpoojaItemId: 'pp-crispy-paneer-wrap',
    name: 'Crispy Paneer Wrap',
    description: 'Golden paneer, bold wrap — a must-try.',
    price: rupees(259),
    category: 'WRAPS & BOWLS',
    isAvailable: true,
    nutrition: n(560, 20, 6),
  },
  {
    petpoojaItemId: 'pp-falafel-wrap',
    name: 'Falafel Wrap',
    description: 'Herby falafel, soft wrap, bright finish.',
    price: rupees(229),
    category: 'WRAPS & BOWLS',
    isAvailable: true,
    nutrition: n(470, 15, 9),
  },

  // —— HUMMUS & GARLIC BREAD ——
  {
    petpoojaItemId: 'pp-hummus-with-falafel',
    name: 'Hummus with Falafel',
    description: 'To share — or not. We will not judge.',
    price: rupees(259),
    category: 'HUMMUS & GARLIC BREAD',
    isAvailable: true,
    nutrition: n(520, 18, 11),
  },
  {
    petpoojaItemId: 'pp-hummus-falafel-pita-pocket',
    name: 'Hummus Falafel Pita Pocket',
    description: 'Pocket-sized, full of crunch.',
    price: rupees(239),
    category: 'HUMMUS & GARLIC BREAD',
    isAvailable: true,
    nutrition: n(480, 16, 10),
  },
  {
    petpoojaItemId: 'pp-garlic-bread',
    name: 'Garlic Bread',
    description: 'Crisp bread, garlic, simple joy.',
    price: rupees(129),
    category: 'HUMMUS & GARLIC BREAD',
    isAvailable: true,
    nutrition: n(320, 7, 2),
  },
  {
    petpoojaItemId: 'pp-butter-garlic-bread',
    name: 'Butter Garlic Bread',
    description: 'Butter-forward, golden edges.',
    price: rupees(149),
    category: 'HUMMUS & GARLIC BREAD',
    isAvailable: true,
    nutrition: n(380, 7, 2),
  },
  {
    petpoojaItemId: 'pp-cheese-garlic-bread',
    name: 'Cheese Garlic Bread',
    description: 'Cheese pull, garlic warmth.',
    price: rupees(189),
    category: 'HUMMUS & GARLIC BREAD',
    isAvailable: true,
    nutrition: n(470, 16, 3),
  },
  {
    petpoojaItemId: 'pp-supreme-garlic-bread',
    name: 'Supreme Garlic Bread',
    description: 'Deep, aromatic, a little fancy.',
    price: rupees(219),
    category: 'HUMMUS & GARLIC BREAD',
    isAvailable: true,
    nutrition: n(520, 18, 5),
  },
  {
    petpoojaItemId: 'pp-cheese-corn-garlic-bread',
    name: 'Cheese Corn Garlic Bread',
    description: 'Sweet corn under a cheese blanket.',
    price: rupees(199),
    category: 'HUMMUS & GARLIC BREAD',
    isAvailable: true,
    nutrition: n(510, 17, 4),
  },
  {
    petpoojaItemId: 'pp-mushroom-garlic-bread',
    name: 'Mushroom Garlic Bread',
    description: 'Earthy mushrooms, garlic warmth.',
    price: rupees(199),
    category: 'HUMMUS & GARLIC BREAD',
    isAvailable: true,
    nutrition: n(500, 17, 4),
  },

  // —— GOURMET SANDWICHES ——
  {
    petpoojaItemId: 'pp-paneer-makhani-sandwich',
    name: 'Paneer Makhani Sandwich',
    description: 'Makhani paneer between warm bread.',
    price: rupees(229),
    category: 'GOURMET SANDWICHES',
    isAvailable: true,
    nutrition: n(560, 22, 5),
  },
  {
    petpoojaItemId: 'pp-veg-spicy-potato-sandwich',
    name: 'Veg Spicy Potato Sandwich',
    description: 'Street spice, cafe calm.',
    price: rupees(179),
    category: 'GOURMET SANDWICHES',
    isAvailable: true,
    nutrition: n(430, 12, 5),
  },
  {
    petpoojaItemId: 'pp-creamy-melt-corn-sandwich',
    name: 'Creamy Melt Corn Sandwich',
    description: 'Sweet corn, pull of cheese.',
    price: rupees(199),
    category: 'GOURMET SANDWICHES',
    isAvailable: true,
    nutrition: n(510, 16, 4),
  },
  {
    petpoojaItemId: 'pp-spinach-corn-sandwich',
    name: 'Spinach & Corn Sandwich',
    description: 'Green, sweet, quietly filling.',
    price: rupees(199),
    category: 'GOURMET SANDWICHES',
    isAvailable: true,
    nutrition: n(480, 17, 6),
  },
  {
    petpoojaItemId: 'pp-mushroom-garlic-sandwich',
    name: 'Mushroom Garlic Sandwich',
    description: 'Earthy mushrooms, garlic warmth.',
    price: rupees(219),
    category: 'GOURMET SANDWICHES',
    isAvailable: true,
    nutrition: n(490, 17, 5),
  },

  // —— NACHOS & SNACKS ——
  {
    petpoojaItemId: 'pp-loaded-taco-chips',
    name: 'Loaded Taco Chips',
    description: 'Chips, toppings, a small celebration.',
    price: rupees(229),
    category: 'NACHOS & SNACKS',
    isAvailable: true,
    nutrition: n(560, 12, 7),
  },
  {
    petpoojaItemId: 'pp-pile-me-up-nachos',
    name: 'Pile Me Up Nachos',
    description: 'Pile high. Pass around.',
    price: rupees(279),
    category: 'NACHOS & SNACKS',
    isAvailable: true,
    nutrition: n(650, 20, 8),
  },
  {
    petpoojaItemId: 'pp-paneer-chaat',
    name: 'Paneer Chaat',
    description: 'Chaat drama, paneer centre stage.',
    price: rupees(199),
    category: 'NACHOS & SNACKS',
    isAvailable: true,
    nutrition: n(360, 18, 4),
  },
  {
    petpoojaItemId: 'pp-mushroom-croquettes',
    name: 'Mushroom Croquettes',
    description: 'Crisp shell, soft mushroom heart.',
    price: rupees(229),
    category: 'NACHOS & SNACKS',
    isAvailable: true,
    nutrition: n(470, 12, 5),
  },
  {
    petpoojaItemId: 'pp-rajma-rice',
    name: 'Rajma Rice',
    description: 'Home on a plate. Soft rajma, warm rice.',
    price: rupees(199),
    category: 'NACHOS & SNACKS',
    isAvailable: true,
    nutrition: n(520, 17, 13),
  },

  // —— FRIES & NIBBLES ——
  {
    petpoojaItemId: 'pp-simple-fries',
    name: 'Simple Fries',
    description: 'Salted, golden, endlessly shareable.',
    price: rupees(149),
    category: 'FRIES & NIBBLES',
    isAvailable: true,
    nutrition: n(420, 5, 5),
  },
  {
    petpoojaItemId: 'pp-peri-peri-fries',
    name: 'Peri-Peri Fries',
    description: 'Our peri-peri — smoky, sharp, signature.',
    price: rupees(179),
    category: 'FRIES & NIBBLES',
    isAvailable: true,
    nutrition: n(435, 5, 5),
  },
  {
    petpoojaItemId: 'pp-truffle-fries',
    name: 'Truffle Fries',
    description: 'Parmesan dust, truffle whisper.',
    price: rupees(249),
    category: 'FRIES & NIBBLES',
    isAvailable: true,
    nutrition: n(490, 8, 5),
  },
  {
    petpoojaItemId: 'pp-loaded-fries',
    name: 'Loaded Fries',
    description: 'Fries that forgot how to travel light.',
    price: rupees(249),
    category: 'FRIES & NIBBLES',
    isAvailable: true,
    nutrition: n(590, 18, 6),
  },

  // —— WOODFIRED PIZZA ——
  {
    petpoojaItemId: 'pp-margherita-pizza',
    name: 'Margherita Pizza',
    description: 'Tomato, mozzarella, the classic quiet flex.',
    price: rupees(299),
    category: 'WOODFIRED PIZZA',
    isAvailable: true,
    nutrition: n(690, 25, 4),
  },
  {
    petpoojaItemId: 'pp-mexican-pizza',
    name: 'Mexican Pizza',
    description: 'Loaded, colourful, made for the middle of the table.',
    price: rupees(329),
    category: 'WOODFIRED PIZZA',
    isAvailable: true,
    nutrition: n(760, 27, 6),
  },
  {
    petpoojaItemId: 'pp-chote-bade-pizza',
    name: 'Chote Bade Pizza',
    description: 'The house pizza. Ours, and soon yours.',
    price: rupees(349),
    category: 'WOODFIRED PIZZA',
    isAvailable: true,
    nutrition: n(790, 30, 7),
  },
  {
    petpoojaItemId: 'pp-chilli-paneer-pizza',
    name: 'Chilli Paneer Pizza',
    description: 'Paneer with a proper chilli spark.',
    price: rupees(379),
    category: 'WOODFIRED PIZZA',
    isAvailable: true,
    nutrition: n(820, 33, 7),
  },
  {
    petpoojaItemId: 'pp-pesto-pizza',
    name: 'Pesto Pizza',
    description: 'Pesto green, soft cheese pearls.',
    price: rupees(399),
    category: 'WOODFIRED PIZZA',
    isAvailable: true,
    nutrition: n(810, 28, 5),
  },

  // —— BURGERS ——
  {
    petpoojaItemId: 'pp-paneer-burger',
    name: 'Paneer Burger',
    description: 'Crisp paneer, stacked with intent.',
    price: rupees(249),
    category: 'BURGERS',
    isAvailable: true,
    nutrition: n(560, 21, 5),
  },
  {
    petpoojaItemId: 'pp-mushroom-burger',
    name: 'Mushroom Burger',
    description: 'Mushrooms melting into the bun.',
    price: rupees(229),
    category: 'BURGERS',
    isAvailable: true,
    nutrition: n(520, 16, 6),
  },
  {
    petpoojaItemId: 'pp-loaded-burger',
    name: 'Loaded Burger',
    description: 'Everything on it. No apologies.',
    price: rupees(279),
    category: 'BURGERS',
    isAvailable: true,
    nutrition: n(650, 24, 6),
  },
  {
    petpoojaItemId: 'pp-aloo-tikki-burger',
    name: 'Aloo Tikki Burger',
    description: 'The familiar tikki, cafe-tall.',
    price: rupees(179),
    category: 'BURGERS',
    isAvailable: true,
    nutrition: n(490, 12, 6),
  },

  // —— FRESH SALADS ——
  {
    petpoojaItemId: 'pp-arabic-fattoush-salad',
    name: 'Arabic Fattoush Salad',
    description: 'Crunch, herbs, lemon lift.',
    price: rupees(229),
    category: 'FRESH SALADS',
    isAvailable: true,
    nutrition: n(290, 7, 7),
  },
  {
    petpoojaItemId: 'pp-caesar-salad',
    name: 'Caesar Salad',
    description: 'The reliable classic, done clean.',
    price: rupees(249),
    category: 'FRESH SALADS',
    isAvailable: true,
    nutrition: n(380, 9, 4),
  },
  {
    petpoojaItemId: 'pp-greek-salad',
    name: 'Greek Salad',
    description: 'Bright, briny, table-resetting.',
    price: rupees(249),
    category: 'FRESH SALADS',
    isAvailable: true,
    nutrition: n(340, 9, 5),
  },

  // —— WAFFLES & PANCAKES ——
  {
    petpoojaItemId: 'pp-banoffee-waffle',
    name: 'Banoffee Waffle',
    description: 'Banana, caramel, waffle pockets.',
    price: rupees(249),
    category: 'WAFFLES & PANCAKES',
    isAvailable: true,
    nutrition: n(590, 9, 5),
  },
  {
    petpoojaItemId: 'pp-nutella-waffle',
    name: 'Nutella Waffle',
    description: 'Hazelnut chocolate, soft waffle dream.',
    price: rupees(299),
    category: 'WAFFLES & PANCAKES',
    isAvailable: true,
    nutrition: n(650, 10, 4),
  },
  {
    petpoojaItemId: 'pp-american-granola-pancake',
    name: 'American Granola Pancake',
    description: 'Stacked pancakes, granola crunch.',
    price: rupees(279),
    category: 'WAFFLES & PANCAKES',
    isAvailable: true,
    nutrition: n(570, 12, 7),
  },
  {
    petpoojaItemId: 'pp-double-choco-chip-pancake',
    name: 'Double Choco Chip Pancake',
    description: 'Chocolate twice — because once is shy.',
    price: rupees(299),
    category: 'WAFFLES & PANCAKES',
    isAvailable: true,
    nutrition: n(610, 11, 5),
  },

  // —— DESSERTS ——
  {
    petpoojaItemId: 'pp-cheesecake',
    name: 'Cheesecake',
    description: 'Dense, cool, unhurried.',
    price: rupees(229),
    category: 'DESSERTS',
    isAvailable: true,
    nutrition: n(510, 8, 1),
  },
  {
    petpoojaItemId: 'pp-tres-leches',
    name: 'Tres Leches',
    description: 'Three milks, one soft slice.',
    price: rupees(229),
    category: 'DESSERTS',
    isAvailable: true,
    nutrition: n(430, 8, 1),
  },
  {
    petpoojaItemId: 'pp-sizzling-brownie-ice-cream',
    name: 'Sizzling Brownie with Ice Cream',
    description: 'Hot brownie, cold ice cream — the finale.',
    price: rupees(279),
    category: 'DESSERTS',
    isAvailable: true,
    nutrition: n(650, 9, 4),
  },
  {
    petpoojaItemId: 'pp-brownie',
    name: 'Brownie',
    description: 'Deep chocolate, no theatrics needed.',
    price: rupees(159),
    category: 'DESSERTS',
    isAvailable: true,
    nutrition: n(420, 6, 3),
  },

  // —— CHOTE BADE BARISTA ——
  {
    petpoojaItemId: 'pp-espresso',
    name: 'Espresso',
    description: 'Short, strong, no small talk.',
    price: rupees(129),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-double-espresso',
    name: 'Double Espresso',
    description: 'Twice the nerve.',
    price: rupees(169),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-americano',
    name: 'Americano',
    description: 'Long black, quietly certain.',
    price: rupees(179),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-cappuccino',
    name: 'Cappuccino',
    description: 'Foam first, then the day begins.',
    price: rupees(199),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-cafe-latte',
    name: 'Café Latte',
    description: 'Milk and espresso in an easy conversation.',
    price: rupees(219),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-flat-white',
    name: 'Flat White',
    description: 'Velvet microfoam, soft strength.',
    price: rupees(229),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-cafe-mocha',
    name: 'Café Mocha',
    description: 'Chocolate meeting coffee, on purpose.',
    price: rupees(249),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-spanish-latte',
    name: 'Spanish Latte',
    description: 'Sweet condensed warmth in a cup.',
    price: rupees(249),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-hazelnut-latte',
    name: 'Hazelnut Latte',
    description: 'Nutty, rounded, afternoon-friendly.',
    price: rupees(249),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-caramel-macchiato',
    name: 'Caramel Macchiato',
    description: 'Caramel drift over espresso.',
    price: rupees(259),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-iced-americano',
    name: 'Iced Americano',
    description: 'Cold, clean, unbothered.',
    price: rupees(199),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-iced-latte',
    name: 'Iced Latte',
    description: 'Chilled milk, steady espresso.',
    price: rupees(229),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-iced-spanish-latte',
    name: 'Iced Spanish Latte',
    description: 'Sweet cold comfort.',
    price: rupees(249),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-iced-mocha',
    name: 'Iced Mocha',
    description: 'Chocolate, coffee, ice.',
    price: rupees(259),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-cold-brew',
    name: 'Cold Brew',
    description: 'Steeped slow. Soft on the nerves.',
    price: rupees(229),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-classic-cold-coffee',
    name: 'Classic Cold Coffee',
    description: 'The one everyone already knows they want.',
    price: rupees(229),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-signature-chote-bade-cold-coffee',
    name: 'Signature Chote Bade Cold Coffee',
    description: 'Our cold coffee — the house pour.',
    price: rupees(279),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-belgian-chocolate-frappe',
    name: 'Belgian Chocolate Frappe',
    description: 'Blended chocolate, cafe-cold.',
    price: rupees(279),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-hazelnut-coffee-frappe',
    name: 'Hazelnut Coffee Frappe',
    description: 'Hazelnut swirl in a cold blend.',
    price: rupees(299),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-caramel-coffee-frappe',
    name: 'Caramel Coffee Frappe',
    description: 'Caramel and coffee, iced thick.',
    price: rupees(299),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-double-chocolate-frappe',
    name: 'Double Chocolate Frappe',
    description: 'Chocolate squared.',
    price: rupees(299),
    category: 'CHOTE BADE BARISTA',
    isAvailable: true,
  },

  // —— REFRESHERS (non-coffee) ——
  {
    petpoojaItemId: 'pp-classic-hot-chocolate',
    name: 'Classic Hot Chocolate',
    description: 'Cocoa warmth in both hands.',
    price: rupees(199),
    category: 'REFRESHERS',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-belgian-hot-chocolate',
    name: 'Belgian Hot Chocolate',
    description: 'Deeper cocoa, slower sip.',
    price: rupees(229),
    category: 'REFRESHERS',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-lemon-iced-tea',
    name: 'Lemon Iced Tea',
    description: 'Bright lemon over cold tea.',
    price: rupees(179),
    category: 'REFRESHERS',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-peach-iced-tea',
    name: 'Peach Iced Tea',
    description: 'Soft peach, easy afternoon.',
    price: rupees(199),
    category: 'REFRESHERS',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-mint-lemon-fizz',
    name: 'Mint Lemon Fizz',
    description: 'Mint, lemon, a clean sparkle.',
    price: rupees(199),
    category: 'REFRESHERS',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-classic-mojito',
    name: 'Classic Mojito',
    description: 'Mint crush, lime lift — virgin and sharp.',
    price: rupees(199),
    category: 'REFRESHERS',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-watermelon-mint-cooler',
    name: 'Watermelon Mint Cooler',
    description: 'Summer in a tall glass.',
    price: rupees(219),
    category: 'REFRESHERS',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-strawberry-lemonade',
    name: 'Strawberry Lemonade',
    description: 'Berry sweet, lemon bright.',
    price: rupees(219),
    category: 'REFRESHERS',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-virgin-berry-fizz',
    name: 'Virgin Berry Fizz',
    description: 'Berries and bubbles.',
    price: rupees(229),
    category: 'REFRESHERS',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-classic-chocolate-shake',
    name: 'Classic Chocolate Shake',
    description: 'Thick, cold, chocolate-forward.',
    price: rupees(229),
    category: 'REFRESHERS',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-strawberry-cream-shake',
    name: 'Strawberry Cream Shake',
    description: 'Pink cream, soft finish.',
    price: rupees(249),
    category: 'REFRESHERS',
    isAvailable: true,
  },
  {
    petpoojaItemId: 'pp-oreo-chocolate-shake',
    name: 'Oreo Chocolate Shake',
    description: 'Cookie crunch in a chocolate shake.',
    price: rupees(279),
    category: 'REFRESHERS',
    isAvailable: true,
  },
]

/** petpoojaItemIds that also appear under Signature Picks on the menu UI. */
export const SIGNATURE_ITEM_IDS = new Set([
  'pp-chote-bade-pizza',
  'pp-makhani-pasta',
  'pp-crispy-paneer-wrap',
  'pp-peri-peri-fries',
  'pp-sizzling-brownie-ice-cream',
])

/** Stable display order matching the printed menu (within and across categories). */
export const MENU_ITEM_ORDER = CAFE_MENU_SEED.map((item) => item.petpoojaItemId)

/** Canonical petpooja IDs — anything else in DB should be retired from the live menu. */
export const CANONICAL_MENU_IDS = new Set(MENU_ITEM_ORDER)
